config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers:{sessions: 'user/sessions'} #esto fue comentado 
  devise_for :admins, controllers: {sessions: "admin/sessions"}
    
  resources :posts do
  resources :comments 
    
end
    root "posts#index"
    get 'alondra_rangel' => 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
    #validacion del texto
    validates :title, presence: true           
    validates :title, length: { in: 5..30 ,    #permite la longitud de valores 
        message: "TITULO INVALIDO!!"}
    
    
    #validacion del contenido
    validates :body, presence: true
    validates :body, length: {minimum:10 ,     #valores minimos permitidos
    message: "El texto de la descripcion es muy corto"}
    validates :body, length: { maximum: 50 ,   #valores maximos permitidos
        message: "El texto de la descripcion es demaciado grande"}
    
    has_many :comments, dependent: :destroy 
    validates_presence_of :title #realiza tablas 
    validates_presence_of :body 

    belongs_to :user

        
      
end


	

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
    
def index
      
 if admin_signed_in?    

@posts = Post.all  

 elsif user_signed_in?

@posts =current_user.posts
    
  end  
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
    

  
def create
 
    
   @post = Post.new(post_params)
    @post.user_id=current_user.id  
  
    respond_to do |format|
      if @post.save
          flash[:success] = "la asesoria se guardo correctamente  ◕ ‿‿ ◕ "
          format.html { redirect_to @post}
          
        format.json { render :show, status: :created, location: @post }
      else
          flash[:alert] = "Ocurrio un error inesperado o(╥﹏╥)o "
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<section class="titulo">
<div class="small-4 columns">
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    </div>
  </div>
</section>


<section class="cuerpo">
 <div class="small-4 columns">
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
      </div>
  </div>
</section>


<section class="row">
    <div class="small-4 columns">
        <div class="actions">
            <%= f.submit 'Aceptar' , :class => 'button small'%>
      </div>
    </div>
</section>



<% end %>

app/views/posts/_navegation.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="menu" data-dropdown-menu>
      <li class="menu-text">Practica rails</li>
      <li>
        
      </li>
      <li><%= link_to "home", controller: "/posts", action: "index" %></li>
      <li>
          <% if user_signed_in? %>
             <%= link_to "nuevo post", controller: "/posts", action: "new" %>
              <% else %>
            
           
          
          <%end%>
          
          
          </li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
        
        <% if user_signed_in? %>
        <li> <strong><%= current_user.email %></strong> </li>
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'top-bar-left' %></li>
       <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'top-bar-left' %> </li>
       
        
        
        <% elsif admin_signed_in? %>
        <li> <strong><%= current_admin.email %></strong> </li>
        <li><%= link_to 'Edit profile', edit_admin_registration_path, :class => 'top-bar-left' %></li>
        <li> <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'top-bar-left' %> </li>
          <% else %> 
        <li> <%= link_to "Sign up", new_user_registration_path, :class => 'top-bar-left' %> </li>
        <li> <%= link_to "Login", new_user_session_path, :class => 'top-bar-left' %> </li>
        <li> <%= link_to "Login admin", new_admin_session_path, :class => 'top-bar-left' %> </li>
        <% end %>
        
    </ul>
  </div>
</div>

      
      
  











  



app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1 class="uno">CONTENIDO DE MIS POSTS</h1>


<table class="TB">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>

        <% if admin_signed_in? %>       
      <th>User</th>   <% end %> 

      <th colspan="3"></th>
        
    

      </tr>
  </thead>

  <tbody>
      <section class="tablas">
          <div class="small-4 columns">
           
              <% @posts.each do |post| %> 
              <tr>
                <td><%= post.title %></td>
                  
                <td>
                <% if post.body.length> 0 %>
                  <a href="#" data-open="post-<%= post.id %>">Ver observaciones</a>
                    <div id="post-<%= post.id %>" class="reveal" data-reveal>
                        <%= post.body %>
                        <button class="close-button" data-close aria-label="cerrar" type="button">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                <% end %>
                 </td>
                  
                  
                  <% if admin_signed_in? %>
            
        <td><%= User.find(post.user_id).email %></td>
               
                  
                  <% end %>
                  
        <% if user_signed_in? %>
            
                  
                <td><%= link_to 'Show', post %></td>
                <td><%= link_to 'Edit', edit_post_path(post) %></td>
                
                  <% end %>
                 
                  

        <% if admin_signed_in? %>
                 
                <td><%= link_to 'Show', post %></td>
                <td><%= link_to 'Edit', edit_post_path(post) %></td>
                  
                <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <% end %>

                  
            </tr>
        </div>
      </section>
    <% end %>
  </tbody>
</table>

<br>


<% if user_signed_in? %>
<%= link_to 'Nuevo post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1 class="NP">NUEVO POST</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>



<div id ="comments">
    <%= render :partial => @post.comments.reverse %>
</div>

<%= form_for([@post, Comment.new],remote: true) do |f| %>

<p><%= f.label :body,"New Comment" %><br/>
    <%= f.text_area :body %>
</p>

<p><%= f.submit "Add Comment", :class => 'button small' %></p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>